server.port=${HTTPS_PORT:8443}
server.http.port=${HTTP_PORT:8080}
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE_PATH:file:./secrets/market-local.p12}
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE:PKCS12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-alias=${SSL_KEY_ALIAS:market-local}