spring.application.name=ziovpo-security-backend

server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
jwt.issuer=${JWT_ISSUER}

logging.level.org.springframework.security=${SECURITY_LOG_LEVEL}
logging.level.com.example.market.security=${APP_SECURITY_LOG_LEVEL}
spring.profiles.active=ssl

signature.key-store-path=classpath:certificates/signing.jks
signature.key-store-type=JKS
signature.key-store-password=${SIGN_KEY_PASS}
signature.key-alias=signing-key
signature.key-password=${SIGN_KEY_PASS}